#!/bin/sh
set -ev
cmake --version

# Enable or disable optional features?
if [ "$1" = "OFF" ]; then
	export OPTEN=OFF
else
	export OPTEN=ON
fi

OPTFEAT="-DENABLE_EXTRA_SECURITY=${OPTEN} -DENABLE_JPEG=${OPTEN} -DENABLE_XML=${OPTEN} -DENABLE_DECRYPTION=${OPTEN} -DENABLE_UNICE68=${OPTEN} -DENABLE_LIBMSPACK=${OPTEN} -DENABLE_PVRTC=${OPTEN} -DENABLE_ZSTD=${OPTEN} -DENABLE_LZ4=${OPTEN} -DENABLE_LZO=${OPTEN} -DENABLE_NLS=${OPTEN} -DENABLE_OPENMP=${OPTEN} -DENABLE_ASTC=${OPTEN}"
BUILD_UI="-DBUILD_KDE4=OFF -DBUILD_KF5=ON -DBUILD_KF6=OFF -DBUILD_XFCE=ON -DBUILD_GTK3=ON -DBUILD_GTK4=ON -DBUILD_CLI=ON"

mkdir build || true
cd build
cmake .. -G Ninja -DBUILD_TESTING=ON -DUSE_XVFB=ON -DENABLE_LTO=OFF -DENABLE_PCH=OFF -DTRACKER_INSTALL_API_VERSION=3 ${OPTFEAT} ${BUILD_UI}
