ignore:
  - "extlib/"
  - "src/libi18n/gettext.h"
  - "src/gtk/tests/"
  - "src/kde/tests/"
  - "src/libcachecommon/tests/"
  - "src/libromdata/tests/"
  - "src/librpbase/tests/"
  - "src/librpbyteswap/tests/"
  - "src/librptext/tests/"
  - "src/librptexture/tests/"
  - "src/rp-download/tests/"
  - "src/win32/tests/"
