
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include <glib-object.h>

/* enumerations from "ListDataItem.h" */
#include "ListDataItem.h"
GType
rp_list_data_item_col0_type_get_type (void)
{
  static gsize static_g_enum_type_id;

  if (g_once_init_enter (&static_g_enum_type_id))
    {
      static const GEnumValue values[] = {
            { RP_LIST_DATA_ITEM_COL0_TYPE_TEXT, "RP_LIST_DATA_ITEM_COL0_TYPE_TEXT", "Text only" },
            { RP_LIST_DATA_ITEM_COL0_TYPE_CHECKBOX, "RP_LIST_DATA_ITEM_COL0_TYPE_CHECKBOX", "Column 0 is a checkbox" },
            { RP_LIST_DATA_ITEM_COL0_TYPE_ICON, "RP_LIST_DATA_ITEM_COL0_TYPE_ICON", "Column 1 is an icon" },
            { RP_LIST_DATA_ITEM_COL0_TYPE_LAST, "RP_LIST_DATA_ITEM_COL0_TYPE_LAST", "last" },
            { 0, NULL, NULL }
      };

      GType g_enum_type_id = g_enum_register_static ("RpListDataItemCol0Type", values);

      g_once_init_leave (&static_g_enum_type_id, g_enum_type_id);
    }
  return static_g_enum_type_id;
}

/* enumerations from "RomDataView.hpp" */
#include "RomDataView.hpp"
GType
rp_desc_format_type_get_type (void)
{
  static gsize static_g_enum_type_id;

  if (g_once_init_enter (&static_g_enum_type_id))
    {
      static const GEnumValue values[] = {
            { RP_DFT_XFCE, "RP_DFT_XFCE", "XFCE style (default)" },
            { RP_DFT_GNOME, "RP_DFT_GNOME", "GNOME style" },
            { RP_DFT_LAST, "RP_DFT_LAST", "last" },
            { 0, NULL, NULL }
      };

      GType g_enum_type_id = g_enum_register_static ("RpDescFormatType", values);

      g_once_init_leave (&static_g_enum_type_id, g_enum_type_id);
    }
  return static_g_enum_type_id;
}

/* enumerations from "config/CacheCleaner.hpp" */
#include "config/CacheCleaner.hpp"
GType
rp_cache_dir_get_type (void)
{
  static gsize static_g_enum_type_id;

  if (g_once_init_enter (&static_g_enum_type_id))
    {
      static const GEnumValue values[] = {
            { RP_CD_System, "RP_CD_System", "System thumbnail cache directory" },
            { RP_CD_RomProperties, "RP_CD_RomProperties", "ROM Properties cache directory" },
            { 0, NULL, NULL }
      };

      GType g_enum_type_id = g_enum_register_static ("RpCacheDir", values);

      g_once_init_leave (&static_g_enum_type_id, g_enum_type_id);
    }
  return static_g_enum_type_id;
}

/* Generated data ends here */

