
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __ROMPROPERTIES_GTK_RP_GTK_ENUMS_ENUM_TYPES_H__
#define __ROMPROPERTIES_GTK_RP_GTK_ENUMS_ENUM_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* enumerations from "RomDataView.hpp" */
GType rp_desc_format_type_get_type (void);
#define RP_TYPE_DESC_FORMAT_TYPE (rp_desc_format_type_get_type())

G_END_DECLS

#endif /* __ROMPROPERTIES_GTK_RP_GTK_ENUMS_ENUM_TYPES_H__ */

/* Generated data ends here */

