
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

#include <glib-object.h>

G_BEGIN_DECLS

/* enumerations from "ListDataItem.h" */
GType rp_list_data_item_col0_type_get_type (void) G_GNUC_CONST;
#define RP_TYPE_LIST_DATA_ITEM_COL0_TYPE (rp_list_data_item_col0_type_get_type ())

/* enumerations from "RomDataView.hpp" */
GType rp_desc_format_type_get_type (void) G_GNUC_CONST;
#define RP_TYPE_DESC_FORMAT_TYPE (rp_desc_format_type_get_type ())

/* enumerations from "CacheCleaner.hpp" */
GType rp_cache_dir_get_type (void) G_GNUC_CONST;
#define RP_TYPE_CACHE_DIR (rp_cache_dir_get_type ())
G_END_DECLS

/* Generated data ends here */

