
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include "rp-gtk-enums.h"

/* enumerations from "RomDataView.hpp" */
#include "RomDataView.hpp"
GType
rp_desc_format_type_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;
  if (g_once_init_enter (&g_define_type_id__volatile)) {
    static const GEnumValue values[] = {
      { RP_DFT_XFCE, "RP_DFT_XFCE", "XFCE style (default)" },
      { RP_DFT_GNOME, "RP_DFT_GNOME", "GNOME style" },
      { RP_DFT_LAST, "RP_DFT_LAST", "last" },
      { 0, NULL, NULL }
    };
    GType g_define_type_id = g_enum_register_static ("RpDescFormatType", values);
    g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
  }
  return g_define_type_id__volatile;
}

/* Generated data ends here */

