usr/lib/*/qt5/plugins/rom-properties-kf5.so
usr/lib/*/qt5/plugins/kf5/propertiesdialog/rom-properties-kf5.so
usr/lib/*/qt5/plugins/kf5/propertiesdialog/xattrview-kf5.so
usr/lib/*/qt5/plugins/kf5/kfilemetadata/kfilemetadata_rom-properties-kf5.so
usr/lib/*/qt5/plugins/kf5/overlayicon/overlayiconplugin_rom-properties-kf5.so
usr/share/kservices5/xattrview-kf5.desktop

# NOTE: Disable or remove this line if the target system has KF5 5.85 or later.
# Ubuntu 18.04: 5.44.0
# Ubuntu 20.04: 5.68.0
# Ubuntu 21.04: 5.80.0
# Ubuntu 21.10: 5.86.0 <-- starting here
# Ubuntu 22.04: 5.98.0
#usr/share/kservices5/rp-convert-to-png.desktop
