# Find Gnome's libnautilus-extension libraries and headers.
# If found, the following variables will be defined:
# - LIBNAUTILUSEXTENSION_FOUND: System has ThunarX.
# - LIBNAUTILUSEXTENSION_INCLUDE_DIRS: ThunarX include directories.
# - LIBNAUTILUSEXTENSION_LIBRARIES: ThunarX libraries.
# - LIBNAUTILUSEXTENSION_DEFINITIONS: Compiler switches required for using ThunarX.
# - LIBNAUTILUSEXTENSION_EXTENSION_DIR: Extensions directory. (for installation)
#
# In addition, a target Gnome::libnautilus-extension will be created with all of
# these definitions.
#
# References:
# - https://cmake.org/Wiki/CMake:How_To_Find_Libraries
# - http://francesco-cek.com/cmake-and-gtk-3-the-easy-way/
#

FIND_PACKAGE(PkgConfig)
IF(PkgConfig_FOUND)
	PKG_CHECK_MODULES(PC_LIBNAUTILUSEXTENSION QUIET libnautilus-extension)
	SET(LIBNAUTILUSEXTENSION_DEFINITIONS ${PC_LIBNAUTILUSEXTENSION_CFLAGS_OTHER})

	FIND_PATH(LIBNAUTILUSEXTENSION_INCLUDE_DIR libnautilus-extension/nautilus-extension-types.h
		HINTS ${PC_LIBNAUTILUSEXTENSION_INCLUDEDIR} ${PC_LIBNAUTILUSEXTENSION_INCLUDE_DIRS})
	FIND_LIBRARY(LIBNAUTILUSEXTENSION_LIBRARY NAMES nautilus-extension libnautilus-extension
		HINTS ${PC_LIBNAUTILUSEXTENSION_LIBDIR} ${PC_LIBNAUTILUSEXTENSION_LIBRARY_DIRS})

	# Handle the QUIETLY and REQUIRED arguments and set LIBNAUTILUSEXTENSION_FOUND to TRUE
	# if all listed variables are TRUE.
	INCLUDE(FindPackageHandleStandardArgs)
	FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBNAUTILUSEXTENSION DEFAULT_MSG LIBNAUTILUSEXTENSION_LIBRARY LIBNAUTILUSEXTENSION_INCLUDE_DIR)
	MARK_AS_ADVANCED(LIBNAUTILUSEXTENSION_INCLUDE_DIR LIBNAUTILUSEXTENSION_LIBRARY)

	SET(LIBNAUTILUSEXTENSION_LIBRARIES ${LIBNAUTILUSEXTENSION_LIBRARY})
	SET(LIBNAUTILUSEXTENSION_INCLUDE_DIRS ${LIBNAUTILUSEXTENSION_INCLUDE_DIR})

	# Create the library target.
	IF(LIBNAUTILUSEXTENSION_FOUND)
		IF(NOT TARGET Gnome::libnautilus-extension)
			ADD_LIBRARY(Gnome::libnautilus-extension UNKNOWN IMPORTED)
		ENDIF(NOT TARGET Gnome::libnautilus-extension)
		SET_TARGET_PROPERTIES(Gnome::libnautilus-extension PROPERTIES
			IMPORTED_LOCATION "${LIBNAUTILUSEXTENSION_LIBRARY}")
		SET_TARGET_PROPERTIES(Gnome::libnautilus-extension PROPERTIES
			COMPILE_DEFINITIONS "${LIBNAUTILUSEXTENSION_DEFINITIONS}")

		# Add include directories from the pkgconfig's Cflags section.
		FOREACH(CFLAG ${PC_LIBNAUTILUSEXTENSION_CFLAGS})
			IF(CFLAG MATCHES "^-I")
				STRING(SUBSTRING "${CFLAG}" 2 -1 INCDIR)
				LIST(APPEND LIBNAUTILUSEXTENSION_INCLUDE_DIRS "${INCDIR}")
				UNSET(INCDIR)
			ENDIF(CFLAG MATCHES "^-I")
		ENDFOREACH()
		SET_TARGET_PROPERTIES(Gnome::libnautilus-extension PROPERTIES
			INTERFACE_INCLUDE_DIRECTORIES "${LIBNAUTILUSEXTENSION_INCLUDE_DIRS}")

		# Extensions directory.
		PKG_GET_VARIABLE(LIBNAUTILUSEXTENSION_EXTENSION_DIR libnautilus-extension extensiondir)
		IF(NOT LIBNAUTILUSEXTENSION_EXTENSION_DIR)
			MESSAGE(FATAL_ERROR "LIBNAUTILUSEXTENSION_EXTENSION_DIR isn't set.")
		ENDIF(NOT LIBNAUTILUSEXTENSION_EXTENSION_DIR)
	ENDIF(LIBNAUTILUSEXTENSION_FOUND)
ENDIF(PkgConfig_FOUND)
