/***************************************************************************
 * ROM Properties Page shell extension. (libromdata)                       *
 * EXENEEntries.cpp: EXE NE Entry ordinal data                             *
 *                                                                         *
 * Copyright (c) 2016-2026 by David Korth.                                 *
 * Copyright (c) 2022 by Egor.                                             *
 * SPDX-License-Identifier: GPL-2.0-or-later                               *
 ***************************************************************************/

#include "EXENEEntries.hpp"

// Needed for ARRAY_SIZE() in EXENEEntries_data.h
#include "common.h"

// C includes
#include "tcharx.h"

// C includes (C++ namespace)
#include <cstring>
#include <cstdlib>

namespace LibRomData { namespace EXENEEntries {

struct OrdinalName {
	uint16_t ordinal;
	uint16_t offset;
};

struct OrdinalNameTable {
	char modname[8];
	const OrdinalName *table;
	size_t count;
};

// generated by EXENEEntries_data.py from wine sources
#include "EXENEEntries_data.h"

/**
 * Look up an ordinal.
 * @param modname The module name
 * @param ordinal The ordinal
 * @return Name for the ordinal, or nullptr if not found.
 */
const char *lookup_ordinal(const char *modname, uint16_t ordinal)
{
	// NOTE: key.modname is *not* NULL-terminated.
	// MSVC's strncpy_s() doesn't like this, so we'll have to
	// do some manual shenanigans.
	OrdinalNameTable key;
	memset(&key, 0, sizeof(key));
	size_t modname_len = strlen(modname);
	assert(modname_len <= sizeof(key.modname));
	if (modname_len > sizeof(key.modname)) {
		// Not possible to match a module name longer than 8 chars.
		return nullptr;
	}
	memcpy(key.modname, modname, modname_len);

	void *ptr = bsearch(&key, entries,
		ARRAY_SIZE(entries), sizeof(entries[0]),
		[](const void *a, const void *b) -> int
		{
			const OrdinalNameTable *const pa = static_cast<const OrdinalNameTable*>(a);
			const OrdinalNameTable *const pb = static_cast<const OrdinalNameTable*>(b);
			return strncasecmp(pa->modname, pb->modname, 8);
		});
	if (!ptr) {
		return nullptr;
	}

	const OrdinalNameTable *const pNameTbl = static_cast<const OrdinalNameTable*>(ptr);
	const OrdinalName key2 = {ordinal, 0};

	ptr = bsearch(&key2, pNameTbl->table,
		pNameTbl->count, sizeof(pNameTbl->table[0]),
		[](const void *a, const void *b) -> int
		{
			const OrdinalName *const pa = static_cast<const OrdinalName*>(a);
			const OrdinalName *const pb = static_cast<const OrdinalName*>(b);
			return (static_cast<int>(pa->ordinal) - static_cast<int>(pb->ordinal));
		});
	if (!ptr) {
		return nullptr;
	}

	const OrdinalName *const pNameInfo = static_cast<const OrdinalName*>(ptr);
	return (likely(pNameInfo->offset != 0) ? &EXENEEntries_strtbl[pNameInfo->offset] : nullptr);
}

} } // namespace LibRomData::EXENEEntries
