/***************************************************************************
 * ROM Properties Page shell extension. (libromdata)                       *
 * EXENEEntries.cpp: EXE NE Entry ordinal data                             *
 *                                                                         *
 * Copyright (c) 2016-2022 by David Korth.                                 *
 * Copyright (c) 2022 by Egor.                                             *
 * SPDX-License-Identifier: GPL-2.0-or-later                               *
 ***************************************************************************/

#include "stdafx.h"
#include "EXENEEntries.hpp"
#include "Other/exe_structs.h"

namespace LibRomData { namespace EXENEEntries {

struct OrdinalName {
	uint16_t ordinal;
	const char *name;
};

struct OrdinalNameTable {
	char modname[8];
	const OrdinalName *table;
	size_t count;
};

// generated by EXENEEntries_data.py from wine sources
#include "EXENEEntries_data.h"

/**
 * Look up an ordinal.
 * @param modname The module name
 * @param ordinal The ordinal
 * @return Name for the ordinal, or nullptr if not found.
 */
const char *lookup_ordinal(const std::string &modname, uint16_t ordinal)
{
	auto it = std::lower_bound(entries, entries+ARRAY_SIZE(entries), modname.c_str(),
		[](const OrdinalNameTable &lhs, const char *rhs) -> bool {
			return strncasecmp(lhs.modname, rhs, 8) < 0;
		});
	if (it == entries+ARRAY_SIZE(entries) || strncasecmp(it->modname, modname.c_str(), 8) != 0)
		return nullptr;

	auto it2 = std::lower_bound(it->table, it->table+it->count, ordinal,
		[](const OrdinalName &lhs, uint16_t rhs) -> bool {
			return lhs.ordinal < rhs;
		});
	if (it2 == it->table+it->count || it2->ordinal != ordinal)
		return nullptr;
	return it2->name;
}

} }
